sudo: required
services:
  - docker

before_install:
  - docker build -t dkapanadze/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dkapanadze/react-test npm test

after_success:
  - docker build -t dkapanadze/multi-client ./client
  - docker build -t dkapanadze/multi-nginx ./nginx
  - docker build -t dkapanadze/multi-server ./server
  - docker build -t dkapanadze/multi-worker ./worker

  #login into docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dkapanadze/multi-client
  - docker push dkapanadze/multi-nginx
  - docker push dkapanadze/multi-server
  - docker push dkapanadze/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-090584472615"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
